kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: powerprotect:discovery-cluster-rolebinding
  labels:
    app.kubernetes.io/part-of: powerprotect.dell.com
  annotations:
    powerprotect.dell.com/version: 20.3.0.0
subjects:
  - kind: ${PPDM_SUBJECT_KIND}
    name: ${PPDM_SUBJECT_NAME}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: powerprotect:discovery-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ppdm-discovery-rolebinding
  namespace: powerprotect
  labels:
    app.kubernetes.io/part-of: powerprotect.dell.com
  annotations:
    powerprotect.dell.com/version: 20.3.0.0
roleRef:
  kind: Role
  name: ppdm-discovery-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ${PPDM_SUBJECT_KIND}
    name: ${PPDM_SUBJECT_NAME}
    apiGroup: rbac.authorization.k8s.io
